##===- unittests/Firehose/Makefile -------------------------*- Makefile -*-===##
##
##                     The KLEE Symbolic Virtual Machine
##
## This file is distributed under the University of Illinois Open Source
## License. See LICENSE.TXT for details.
##
##===----------------------------------------------------------------------===##

LEVEL := ../..
include $(LEVEL)/Makefile.config

TESTNAME := Firehose
USEDLIBS := kleeBasic.a kleeSupport.a
LINK_COMPONENTS := support

include $(LLVM_SRC_ROOT)/unittests/Makefile.unittest
